name: expensify_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  dio: ^5.6.0
  dotted_border: ^2.1.0
  firebase_auth: null
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_dash: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  path_provider: ^2.1.4
  pdf: ^3.11.1
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  printing: ^5.12.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/expensify_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
